#!/usr/bin/env racket
#lang sicp

(define (timed-prime-test n)
  (define (start-prime-test n start-time)
    (if (fast-prime? n 7)
        (report-prime (- (runtime) start-time))
        false))
  (define (report-prime elapsed-time)
    (newline)
    (display n)
    (display " *** ")
    (display elapsed-time))
  (start-prime-test n (runtime)))

(define (square x) (* x x))
(define (expmod base exp m)
  (remainder (fast-expt base exp) m))
(define (fast-expt b n)
  (cond ((= n 0) 1)
        ((even? n) (square (fast-expt b (/ n 2))))
        (else (* b (fast-expt b (- n 1))))))
(define (fermat-test n)
  (define (try-it a)
    (= (expmod a n n) a))
  (try-it (+ 1 (random (- n 1)))))
(define (fast-prime? n times)
  (cond ((= times 0) true)
        ((fermat-test n) (fast-prime? n (- times 1)))
        (else false)))

(define (even? n)
  (= (remainder n 2) 0))

(define (search-for-primes start)
  (define (prime-searcher curr num-primes stop)
    (cond ((= num-primes stop) (newline) (display "End"))
          ((timed-prime-test curr)
           (prime-searcher (+ curr 2) (+ num-primes 1) stop))
          (else (prime-searcher (+ curr 2) num-primes stop))))
  (if (even? start)
    (prime-searcher (+ start 1) 0 3)
    (prime-searcher start 0 3)))

(search-for-primes 10)
(search-for-primes 100)
(search-for-primes 1000)
(search-for-primes 10000)
(search-for-primes 100000)
(search-for-primes 1000000)
(search-for-primes 10000000)
(search-for-primes 100000000)
(search-for-primes 1000000000)
