#!/usr/bin/env racket
#lang sicp

(define (timed-prime-test-old n)
  (define (start-prime-test n start-time)
    (if (prime?-old n)
        (report-prime (- (runtime) start-time))
        false))
  (define (report-prime elapsed-time)
    (newline)
    (display n)
    (display " *** ")
    (display elapsed-time))
  (start-prime-test n (runtime)))
(define (timed-prime-test-new n)
  (define (start-prime-test n start-time)
    (if (prime?-new n)
        (report-prime (- (runtime) start-time))
        false))
  (define (report-prime elapsed-time)
    (newline)
    (display n)
    (display " *** ")
    (display elapsed-time))
  (start-prime-test n (runtime)))

(define (smallest-divisor-old n)
  (define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((divides? test-divisor n) test-divisor)
          (else (find-divisor n (+ test-divisor 1)))))
  (define (square x) (* x x))
  (define (divides? a b) (= (remainder b a) 0))
  (find-divisor n 2))
(define (smallest-divisor-new n)
  (define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((divides? test-divisor n) test-divisor)
          (else (find-divisor n (next test-divisor)))))
  (define (next n)
    (if (= n 2) 3 (+ n 2)))
  (define (square x) (* x x))
  (define (divides? a b) (= (remainder b a) 0))
  (find-divisor n 2))

(define (prime?-old n)
  (= n (smallest-divisor-old n)))
(define (prime?-new n)
  (= n (smallest-divisor-new n)))

(define (even? n)
  (= (remainder n 2) 0))

(define (search-for-primes-old start)
  (define (prime-searcher curr num-primes stop)
    (cond ((= num-primes stop) (newline) (display "End"))
          ((timed-prime-test-old curr)
           (prime-searcher (+ curr 2) (+ num-primes 1) stop))
          (else (prime-searcher (+ curr 2) num-primes stop))))
  (if (even? start)
    (prime-searcher (+ start 1) 0 3)
    (prime-searcher start 0 3)))
(define (search-for-primes-new start)
  (define (prime-searcher curr num-primes stop)
    (cond ((= num-primes stop) (newline) (display "End"))
          ((timed-prime-test-new curr)
           (prime-searcher (+ curr 2) (+ num-primes 1) stop))
          (else (prime-searcher (+ curr 2) num-primes stop))))
  (if (even? start)
    (prime-searcher (+ start 1) 0 3)
    (prime-searcher start 0 3)))

(search-for-primes-old 1000000000)
(search-for-primes-old 10000000000)
(search-for-primes-old 100000000000)
(search-for-primes-new 1000000000)
(search-for-primes-new 10000000000)
(search-for-primes-new 100000000000)
