#!/usr/bin/env racket
#lang sicp

(#%require "sqrt.rkt")
(#%require "pi.rkt")

(#%provide make-rect-pt)
(#%provide make-rect-dm)
(#%provide make-rect-di)
(#%provide make-point)
(#%provide make-segment)
(#%provide deg-to-rad)
(#%provide print-points)
(#%provide print-dimensions)
(#%provide perimeter)
(#%provide area)

(define pt 1)
(define dm 2)
(define di 3)

(define (get-type rect) (car rect))

(define (make-rect-pt p1 p2 p3 p4)
  (define (sort-by-y g1 g2 g3 g4)
    (cond ((< (y-point g1) (y-point g2))
           (sort-by-y g2 g1 g3 g4))
          ((< (y-point g2) (y-point g3))
           (sort-by-y g1 g3 g2 g4))
          ((< (y-point g3) (y-point g4))
           (sort-by-y g1 g2 g4 g3))
          (else (cons (cons g4 g3) (cons g2 g1)))))
  (let ((sorted-y (sort-by-y p1 p2 p3 p4)))
    (define (sort-by-x g1 g2)
      (if (< (x-point g1) (x-point g2))
          (cons g2 g1)
          (cons g1 g2)))
    (let ((first-batch (sort-by-x
                         (car (car sorted-y))
                         (cdr (car sorted-y))))
          (second-batch (sort-by-x
                          (car (cdr sorted-y))
                          (cdr (cdr sorted-y)))))
      (let ((p1 (cdr first-batch))
            (p2 (car first-batch))
            (p3 (cdr second-batch))
            (p4 (car second-batch)))
        (if (orthoganality-test p1 p2 p3)
            (cons pt
                  (cons (cons p1 p2)
                        (cons p3 p4)))
            (display "Not a valid rectangle"))))))

(define tolerance 0.0001)
(define (orthoganality-test p1 p2 p3)
  (let ((u (cons (- (x-point p2) (x-point p1))
                 (- (y-point p2) (y-point p1))))
        (v (cons (- (x-point p3) (x-point p1))
                 (- (y-point p3) (y-point p1)))))
    (< (abs (+ (* (car u) (car v)) 
               (* (cdr u) (cdr v)))) 
       tolerance)))

(define (select-point rect-pt n)
  (cond ((= n 1) (car (car (cdr rect-pt))))
        ((= n 2) (cdr (car (cdr rect-pt))))
        ((= n 3) (car (cdr (cdr rect-pt))))
        ((= n 4) (cdr (cdr (cdr rect-pt))))))

(define (sort v1 v2 v3 v4)
  (cond ((< v1 v2) (sort v2 v1 v3 v4))
        ((< v2 v3) (sort v1 v3 v2 v4))
        ((< v3 v4) (sort v1 v2 v4 v3))
        (else (make-rect-pt v1 v2 v3 v4))))

(define (dim-pt rect-pt condition)
  (let ((a1 (- (x-point (select-point rect-pt 2))
               (x-point (select-point rect-pt 1))))
        (b1 (- (y-point (select-point rect-pt 2))
               (y-point (select-point rect-pt 1))))
        (a2 (- (x-point (select-point rect-pt 1))
               (x-point (select-point rect-pt 3))))
        (b2 (- (y-point (select-point rect-pt 3))
               (y-point (select-point rect-pt 1)))))
    (let ((dim1 (sqrt (+ (* a1 a1) (* b1 b1))))
          (dim2 (sqrt (+ (* a2 a2) (* b2 b2)))))
      (condition dim1 dim2))))
(define (length-pt rect-pt)
  (dim-pt rect-pt
          (lambda (x y) (if (> x y) x y))))
(define (width-pt rect-pt)
  (dim-pt rect-pt
          (lambda (x y) (if (> x y) y x))))

(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))

(define (make-rect-dm length width origin angle)
  (cons dm (cons (cons length width) (cons origin angle))))
(define (length-dm rect-dm) (car (car (cdr rect-dm))))
(define (width-dm rect-dm) (cdr (car (cdr rect-dm))))
(define (origin-dm rect-dm) (car (cdr (cdr rect-dm))))
(define (angle-dm rect-dm) (cdr (cdr (cdr rect-dm))))

(define (make-segment p1 p2) (cons p1 p2))
(define (start-segment seg) (car seg))
(define (end-segment seg) (cdr seg))

(define (deg-to-rad x)
  (/ (* x pi) 180))

(define (get-points rect)
  (cond ((= (get-type rect) pt) rect)
        ((= (get-type rect) dm)
         (let ((p1 (origin rect))
               (length (length rect))
               (width (width rect))
               (angle (angle rect))
               (90-deg (deg-to-rad 90)))
           (let ((p2 (make-point
                       (+ (x-point p1) (* (cos angle) width))
                       (+ (y-point p1) (* (sin angle) width))))
                 (p3 (make-point
                       (- (x-point p1) (* (cos (- 90-deg angle)) length))
                       (+ (y-point p1) (* (sin (- 90-deg angle)) length)))))
             (let ((p4 (make-point
                         (- (x-point p2) (* (cos (- 90-deg angle)) length))
                         (+ (y-point p3) (* (sin angle) width)))))
               (make-rect-pt p1 p2 p3 p4)))))
        ((= (get-type rect) di)
         (let ((p1 (start-segment (diag1 rect)))
               (p2 (end-segment (diag1 rect)))
               (p3 (start-segment (diag2 rect)))
               (p4 (end-segment (diag2 rect))))
           (make-rect-pt p1 p2 p3 p4)))))

(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")")
  (newline))

(define (print-points rect)
  (cond ((= (get-type rect) pt)
         (print-point (select-point rect 1))
         (print-point (select-point rect 2))
         (print-point (select-point rect 3))
         (print-point (select-point rect 4)))
        ((= (get-type rect) dm)
         (print-points (get-points rect)))
        ((= (get-type rect) di)
         (print-points (get-points rect)))))

(define (arctan x)
  (+ (- x (/ (* x x x) 3)) (/ (* x x x x x) 5)))
(define (get-dimensions rect)
  (cond ((= (get-type rect) pt)
         (let ((origin (select-point rect 1)))
           (make-rect-dm
             (length rect)
             (width rect)
             origin
             (arctan (/ (- (y-point (select-point rect 2))
                           (y-point origin))
                        (- (x-point (select-point rect 2))
                           (x-point origin)))))))
        ((= (get-type rect) dm) rect)
        ((= (get-type rect) di)
         (get-dimensions (get-points rect)))))

(define (origin rect)
  (cond ((= (get-type rect) pt) (origin (get-dimensions rect)))
        ((= (get-type rect) dm) (origin-dm rect))
        ((= (get-type rect) di) (origin (get-dimensions rect)))))
(define (angle rect)
  (cond ((= (get-type rect) pt) (angle (get-dimensions rect)))
        ((= (get-type rect) dm) (angle-dm rect))
        ((= (get-type rect) di) (angle (get-dimensions rect)))))

(define (print-dimensions rect)
  (cond ((= (get-type rect) pt)
         (print-dimensions (get-dimensions rect)))
        ((= (get-type rect) dm)
         (display "length: ")
         (display (length rect))
         (newline)
         (display "width: ")
         (display (width rect))
         (newline)
         (display "origin: ")
         (print-point (origin rect))
         (display "angle (deg): ")
         (display (/ (* 180 (angle rect)) pi))
         (newline))
        ((= (get-type rect) di)
         (print-dimensions (get-dimensions rect)))))

(define (make-rect-di diag1 diag2) 
  (cons di (cons diag1 diag2)))
(define (diag1 rect) (car (cdr rect)))
(define (diag2 rect) (cdr (cdr rect)))
(define (length-di rect-di) (length-pt (get-points rect-di)))
(define (width-di rect-di) (width-pt (get-points rect-di)))

(define (perimeter rect)
  (* 2 (+ (length rect) (width rect))))
(define (area rect) (* (length rect) (width rect)))

(define (length rect)
  (cond ((= (get-type rect) pt) (length-pt rect))
        ((= (get-type rect) dm) (length-dm rect))
        ((= (get-type rect) di) (length-di rect))))
(define (width rect)
  (cond ((= (get-type rect) pt) (width-pt rect))
        ((= (get-type rect) dm) (width-dm rect))
        ((= (get-type rect) di) (width-di rect))))
