#!/usr/bin/env racket
#lang sicp

(#%provide put)
(#%provide put-coercion)
(#%provide get)
(#%provide get-coercion)
(#%provide attach-tag)
(#%provide type-tag)
(#%provide contents)
(#%provide table)
(#%provide coercion-table)

(define table '())
(define coercion-table '())

(define get-op car)
(define get-types cadr)
(define get-proc caddr)

(define (put op types proc)
  (set! table (append table (list (list op types proc)))))
(define (put-coercion type1 type2 proc)
  (set! coercion-table (append coercion-table
                               (list (list type1 type2 proc)))))
(define (get op types)
  (iter op types table))
(define (get-coercion type1 type2)
  (iter type1 type2 coercion-table))
(define (iter op types table)
  (cond ((null? table) #f)
        ((and (equal? (get-op (car table)) op)
              (valid-types? types (get-types (car table))))
         (get-proc (car table)))
        (else (iter op types (cdr table)))))

(define (valid-types? given-types table-types)
  (define (in-types? given-type table-types)
    (cond ((null? table-types) #f)
          ((not (pair? table-types))
           (if (eq? given-type table-types) #t #f))
          ((eq? given-type (car table-types)) #t)
          (else (in-types? given-type (cdr table-types)))))
  (cond ((null? given-types) #t)
        ((not (pair? given-types))
         (if (in-types? given-types table-types) #t #f))
        ((in-types? (car given-types) table-types)
         (valid-types? (cdr given-types) table-types))
        (else #f)))

(define (attach-tag type-tag contents)
  (cons type-tag contents))
(define (type-tag datum)
  (cond ((number? datum) 'integer)
        ((pair? datum) (car datum))
        (else (error "Bad tagged datum: TYPE-TAG" datum))))
(define (contents datum)
  (cond ((number? datum) datum)
        ((pair? datum) (cdr datum))
        (else (error "Bad tagged datum: TYPE-TAG" datum))))
