#!/usr/bin/env racket
#lang sicp

(define (deriv exp var)
  (cond ((number? exp) 0)
        ((variable? exp) (if (same-variable? exp var) 1 0))
        (else ((get 'deriv (operator exp))
               (operands exp) var))))
(define (operator exp) (car exp))
(define (operands exp) (cdr exp))

(define (install-deriv-package)
  ;; internal procedures
  (define (deriv-sum sum var)
    (make-sum (deriv (addend sum) var)
              (deriv (augend sum) var)))
  (define (deriv-product product var)
    (make-sum (make-product (multiplier product)
                            (deriv (multiplicand product) var))
              (make-product (deriv (multiplier product) var)
                            (multiplicand product))))
  (define (make-sum addend augend)
    (cond ((=number? addend 0) augend)
          ((=number? augend 0) addend)
          ((and (number? addend) (number? augend))
           (+ addend augend))
          (else (list '+ addend augend))))
  (define (addend sum) (cadr sum))
  (define (augend sum) (caddr sum))
  (define (make-product multiplier multiplicand)
    (cond ((or (=number? multiplier 0)
               (=number? multiplicand 0)) 0)
          ((=number? multiplier 1) multiplicand)
          ((=number? multiplicand 1) multiplier)
          ((and (number? multiplier) (number? multiplicand))
           (* multiplier multiplicand))
          (else (list ('* multiplier multiplicand)))))
  (define (multiplier product) (cadr product))
  (define (multiplicand product) (caddr product))
  (define (deriv-exponent exponent var)
    (make-product
      (make-product (power exponent)
                    (make-exponent (base exponent)
                                   (- (power exponent) 1)))
      (deriv (base exponent) var)))
  (define (make-exponent base power)
    (cond ((=number? power 0) 1)
          ((=number? power 1) base)
          (else (list ('** base power)))))
  (define (base exponent) (cadr exponent))
  (define (power exponent) (caddr exponent))

  ;; interface to the rest of the system
  (put 'deriv '(+) deriv-sum)
  (put 'deriv '(*) deriv-product)
  (put 'deriv '(**) deriv-exponent)
  'done)
