#!/usr/bin/env racket
#lang sicp

(#%require "general-arithmetic.rkt")

(define (adjoin-term term term-list)
  (let ((curr-order (length term-list)))
    (cond ((= (order term) curr-order)
           (cons (coeff term) term-list))
          ((> (order term) curr-order)
           (adjoin-term term (cons 0 term-list)))
          ((< (order term) curr-order)
           (if (=zero? (car term-list))
               (adjoin-term term (cdr term-list))
               (cons (car term-list)
                     (adjoin-term term (cdr term-list))))))))
(define (first-term term-list)
  ;; construct so that it is order coeff list form
  (define (iter term-list order-count)
    (cond ((null? term-list)
           (error "Empty term list" term-list))
          ((not (=zero? (car term-list)))
           (list order-count (car term-list)))
          (else (iter (cdr term-list) (- order-count 1)))))
  (iter term-list (- (length term-list) 1)))
(define (rest-terms term-list)
  (cond ((null? term-list)
         (error "Empty term list" term-list))
        ((not (=zero? (car term-list)))
         (cdr term-list))
        (else (rest-terms (cdr term-list)))))
(define (the-empty-termlist) '())
(define (empty-termlist? term-list)
  (cond ((null? term-list) #t)
        ((all-zeros? term-list) #t)
        (else #f)))
(define (all-zeros? term-list)
  (cond ((null? term-list) #t)
        ((=zero? (coeff (car term-list)))
         (all-zeros? (cdr term-list)))
        (else #f)))
(define (make-term order coeff) (list order coeff))
(define (order term) (car term))
(define (coeff term) (cadr term)) 

(adjoin-term (make-term 5 1)
             (adjoin-term (make-term 4 2)
                          (adjoin-term (make-term 2 3)
                                       (adjoin-term (make-term 1 -2)
                                                    (adjoin-term (make-term 0 -5)
                                                                 (the-empty-termlist))))))

(adjoin-term (make-term 100 1)
             (adjoin-term (make-term 2 2)
                          (adjoin-term (make-term 0 1)
                                       (the-empty-termlist))))
