#!/usr/bin/env racket
#lang sicp

(define (make-account balance password)
  (let ((attempts 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch pw req)
      (if (eq? pw password)
          (begin (set! attempts 0)
                 (cond ((eq? req 'withdraw) withdraw)
                        ((eq? req 'deposit) deposit)
                        (else (error "Unknown request: MAKE-ACCOUNT"
                                     req))))
          (begin (set! attempts (+ attempts 1))
                 (lambda (amount)
                   (if (> attempts 7)
                       (call-the-cops)
                       "Incorrect password")))))
    dispatch))

(define (call-the-cops) "Cops have been called!")

(define acc (make-account 100 'secret-password))
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'secret-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
((acc 'wrong-password 'withdraw) 40)
